server:
  port: 8081

spring:
  application:
    name: identity-access-service
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations:
      - "classpath:db/migration"

keycloak:
  server-url: http://localhost:8180
  master-realm: master
  admin-client-id: admin-cli
  admin-client-secret: <your-admin-cli-secret>
